# Generated by Django 4.2.11 on 2025-12-01 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KintoneConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='用于识别此Kintone连接', max_length=100, verbose_name='连接名称')),
                ('subdomain', models.CharField(help_text='例如：your-company（不含.cybozu.com）', max_length=100, verbose_name='子域名')),
                ('auth_type', models.CharField(choices=[('password', '密码认证'), ('api_token', 'API Token认证')], default='api_token', max_length=20, verbose_name='认证方式')),
                ('username', models.CharField(blank=True, help_text='密码认证时使用', max_length=100, verbose_name='用户名')),
                ('password', models.CharField(blank=True, help_text='密码认证时使用', max_length=255, verbose_name='密码')),
                ('api_token', models.CharField(blank=True, help_text='API Token认证时使用', max_length=255, verbose_name='API Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('use_guest_space', models.BooleanField(default=False, verbose_name='使用来宾空间')),
                ('guest_space_id', models.CharField(blank=True, max_length=20, verbose_name='来宾空间ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'Kintone连接',
                'verbose_name_plural': 'Kintone连接',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KintoneApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=20, verbose_name='应用ID')),
                ('app_name', models.CharField(max_length=200, verbose_name='应用名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('total_requests', models.IntegerField(default=0, verbose_name='总请求次数')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='最后访问时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='kintone_api.kintoneconnection', verbose_name='连接')),
            ],
            options={
                'verbose_name': 'Kintone应用',
                'verbose_name_plural': 'Kintone应用',
                'ordering': ['connection', 'app_name'],
                'unique_together': {('connection', 'app_id')},
            },
        ),
        migrations.CreateModel(
            name='KintoneRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('get_records', '获取记录'), ('get_record', '获取单条记录'), ('add_record', '添加记录'), ('update_record', '更新记录'), ('delete_records', '删除记录'), ('get_app_info', '获取应用信息'), ('get_form_fields', '获取表单字段'), ('upload_file', '上传文件'), ('download_file', '下载文件'), ('other', '其他')], max_length=50, verbose_name='操作类型')),
                ('request_url', models.TextField(verbose_name='请求URL')),
                ('request_method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('request_params', models.JSONField(blank=True, null=True, verbose_name='请求参数')),
                ('request_body', models.TextField(blank=True, null=True, verbose_name='请求体')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='状态码')),
                ('response_body', models.TextField(blank=True, null=True, verbose_name='响应体')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='响应时间(秒)')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('error', '错误')], max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='调用时间')),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='kintone_api.kintoneapp', verbose_name='应用')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kintone_api.kintoneconnection', verbose_name='连接')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='调用用户')),
            ],
            options={
                'verbose_name': 'Kintone请求日志',
                'verbose_name_plural': 'Kintone请求日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='kintone_api_created_f525f5_idx'), models.Index(fields=['status'], name='kintone_api_status_5c3c73_idx'), models.Index(fields=['action'], name='kintone_api_action_c69dcd_idx')],
            },
        ),
        migrations.CreateModel(
            name='KintoneFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_code', models.CharField(max_length=100, verbose_name='字段代码')),
                ('field_name', models.CharField(max_length=200, verbose_name='字段名称')),
                ('field_type', models.CharField(help_text='例如：SINGLE_LINE_TEXT, NUMBER, DATE等', max_length=50, verbose_name='字段类型')),
                ('external_field_name', models.CharField(blank=True, help_text='映射到其他系统的字段名', max_length=200, verbose_name='外部字段名')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='kintone_api.kintoneapp', verbose_name='应用')),
            ],
            options={
                'verbose_name': 'Kintone字段映射',
                'verbose_name_plural': 'Kintone字段映射',
                'ordering': ['app', 'field_code'],
                'unique_together': {('app', 'field_code')},
            },
        ),
    ]
