# Generated by Django 4.2.11 on 2025-12-01 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='端点名称')),
                ('service', models.CharField(choices=[('teams', 'Microsoft Teams'), ('outlook', 'Outlook'), ('sharepoint', 'SharePoint'), ('graph', 'Microsoft Graph (通用)')], max_length=50, verbose_name='服务类型')),
                ('endpoint_url', models.CharField(help_text='相对于 https://graph.microsoft.com/v1.0/ 的路径', max_length=500, verbose_name='端点URL')),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10, verbose_name='HTTP方法')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('requires_body', models.BooleanField(default=False, verbose_name='需要请求体')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('total_calls', models.IntegerField(default=0, verbose_name='总调用次数')),
                ('last_called', models.DateTimeField(blank=True, null=True, verbose_name='最后调用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'API端点',
                'verbose_name_plural': 'API端点',
                'ordering': ['service', 'name'],
            },
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='用于识别此Token的名称', max_length=100, verbose_name='Token名称')),
                ('client_id', models.CharField(max_length=255, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=255, verbose_name='Client Secret')),
                ('tenant_id', models.CharField(max_length=255, verbose_name='Tenant ID')),
                ('access_token', models.TextField(blank=True, null=True, verbose_name='Access Token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Token过期时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'API Token',
                'verbose_name_plural': 'API Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('subject', models.CharField(max_length=255, verbose_name='邮件主题')),
                ('body_template', models.TextField(help_text='支持HTML和变量', verbose_name='邮件正文模板')),
                ('default_recipients', models.TextField(blank=True, help_text='多个邮箱用逗号分隔', verbose_name='默认收件人')),
                ('default_cc', models.TextField(blank=True, help_text='多个邮箱用逗号分隔', verbose_name='默认抄送')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '邮件模板',
                'verbose_name_plural': '邮件模板',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('channel_id', models.CharField(blank=True, max_length=255, verbose_name='频道ID')),
                ('team_id', models.CharField(blank=True, max_length=255, verbose_name='团队ID')),
                ('chat_id', models.CharField(blank=True, max_length=255, verbose_name='聊天ID')),
                ('message_template', models.TextField(help_text='支持变量，如 {user_name}, {message}', verbose_name='消息模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Teams消息模板',
                'verbose_name_plural': 'Teams消息模板',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('request_url', models.TextField(verbose_name='请求URL')),
                ('request_body', models.TextField(blank=True, null=True, verbose_name='请求体')),
                ('request_headers', models.JSONField(blank=True, null=True, verbose_name='请求头')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='状态码')),
                ('response_body', models.TextField(blank=True, null=True, verbose_name='响应体')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='响应时间(秒)')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('error', '错误')], max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='调用时间')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='microsoft_api.apiendpoint', verbose_name='API端点')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='microsoft_api.apitoken', verbose_name='使用的Token')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='调用用户')),
            ],
            options={
                'verbose_name': 'API使用日志',
                'verbose_name_plural': 'API使用日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='microsoft_a_created_293257_idx'), models.Index(fields=['status'], name='microsoft_a_status_d2acd8_idx'), models.Index(fields=['endpoint', '-created_at'], name='microsoft_a_endpoin_1962f3_idx')],
            },
        ),
    ]
